# Details of application creation, signing and notarisation: https://developer.apple.com/forums/thread/128166
name: appreleaser
on:
  push:
    tags:
      - "cosmos-*"

jobs:

  build-and-release:
    runs-on: macos-12
    steps:

      - uses: actions/checkout@v3

      - uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MAC_INST_CERTIFICATE }}
          p12-password: ${{ secrets.MAC_INST_CERTIFICATE_PASSPHRASE }}

      - name: Download artifacts, build and sign package
        run: |
          ./compile-package-content.sh "${{ github.ref_name }}"
          productbuild --distribution Distribution --resources Resources "./${{ github.ref_name }}.pkg" --timestamp --sign "${{ secrets.MAC_INST_CERTIFICATE_CN }}"

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fail_on_unmatched_files: true
          files: ${{ github.ref }}.pkg
